Repository GSG-G7/HotMeal, pull requests merged in 2019-10, with the labels that each got.

#56 common popup component is created and styled
  client/package-lock.json
  client/public/index.html
  client/src/assets/images/largesecreen.svg
  client/src/assets/images/popupImg.png
  client/src/assets/images/popupimg.svg
  client/src/components/App/style.css
  client/src/components/utils/PopUp/index.js
  client/src/components/utils/PopUp/style.css
Labels: Approved

#64 38 login component
  client/package-lock.json
  client/package.json
  client/src/components/App/index.js
  client/src/components/pages/Error404/index.js
  client/src/components/pages/Error404/style.css
  client/src/components/pages/Login/index.js
  client/src/components/pages/Login/style.css
  client/src/validation/login.js
Labels: Approved

#59 Meals page
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/screen-0.jpg
  client/src/components/App/index.js
  client/src/components/App/style.css
  client/src/components/MealPage/CardMeal.js
  client/src/components/MealPage/Category.js
  client/src/components/MealPage/MealList.js
  client/src/components/MealPage/index.js
  client/src/components/MealPage/style.css
  client/src/components/mealPage/CardMeal.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
Labels: Awaiting Review

#61 34 feedback component
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/images/feedback.png
  client/src/components/App/index.js
  client/src/components/App/style.css
  client/src/components/feedback/index.js
  client/src/components/feedback/style.css
  client/src/components/utils/PopUp/style.css
  client/src/validation/feedback.js
  server/app.js
  server/controllers/index.js
Labels: Approved

#66 Auth
  client/src/components/App/index.js
  client/src/components/Auth/Auth.js
  server/controllers/index.js
  server/controllers/isAuth.js
Labels: Awaiting Review

#62 Details page
  client/package-lock.json
  client/public/index.html
  client/src/assets/shrimppizza.jpg
  client/src/components/App/index.js
  client/src/components/App/style.css
  client/src/components/DetailsPage/index.js
  client/src/components/DetailsPage/style.css
  client/src/components/MealPage/CardMeal.js
  client/src/components/MealPage/MealList.js
  client/src/components/MealPage/style.css
  client/src/components/home/slider/slider.css
Labels: Changes Requested
